# -*- coding: utf-8 -*-
"""AH40227.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gOkvCKCUPscjYjztUvCew-L7-W-09s-U

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew, kurtosis

sns.set(style="whitegrid")

"""Load Dataset"""

df = pd.read_csv("netflix_titles.csv")

"""Initial Inspection"""

print("Dataset Shape:", df.shape)
print(df.head())

"""Data Cleaning"""

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Convert date_added to datetime
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

# Extract year added
df["year_added"] = df["date_added"].dt.year

# Handle missing values
df["director"].fillna("Unknown", inplace=True)
df["cast"].fillna("Unknown", inplace=True)
df["country"].fillna("Unknown", inplace=True)
df["rating"].fillna("Unknown", inplace=True)

# Separate duration for Movies
movies = df[df["type"] == "Movie"].copy()
movies["duration"] = movies["duration"].str.replace(" min", "")
movies["duration"] = pd.to_numeric(movies["duration"], errors="coerce")

# Drop missing duration values
movies = movies.dropna(subset=["duration"])

print("Cleaned Movie Dataset Shape:", movies.shape)

"""Statistical Moments"""

mean_duration = movies["duration"].mean()
variance_duration = movies["duration"].var()
skewness_duration = skew(movies["duration"])
kurtosis_duration = kurtosis(movies["duration"])

print("\nStatistical Moments for Movie Duration:")
print("Mean:", round(mean_duration, 2))
print("Variance:", round(variance_duration, 2))
print("Skewness:", round(skewness_duration, 2))
print("Kurtosis:", round(kurtosis_duration, 2))

"""Categorical Plot"""

plt.figure(figsize=(8,5))
sns.countplot(data=df, x="type")
plt.title("Distribution of Content Type on Netflix")
plt.xlabel("Type")
plt.ylabel("Count")
plt.show()

"""Relational Plot"""

plt.figure(figsize=(10,6))
sns.scatterplot(data=movies, x="release_year", y="duration", alpha=0.4)
plt.title("Release Year vs Movie Duration")
plt.xlabel("Release Year")
plt.ylabel("Duration (minutes)")
plt.show()

"""Statistical Plot"""

numeric_df = movies[["release_year", "duration", "year_added"]]

plt.figure(figsize=(6,5))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()